In [195]:
import pandas as pd
import numpy as np

### Исходные данные

In [196]:
kriteria_alternatives_kriteria = [K1_A, K2_A, K3_A, K4_A, K5_A]
K1_A = [[1, 3], [float(1/3), 1]]
K2_A = [[1, 4], [0.25, 1]]
K3_A = [[1, 0.2], [5, 1]]
K4_A = [[1, 0.125], [8, 1]]
K5_A = [[1, 6], [float(1/6), 1]]

In [197]:
target_kriterias = [T1_K, T2_K]
T1_K = [[1, 2, 0.5, 1, 1],
        [0.5, 1, 2, 2, 1],
        [2, 0.5, 1, 1, 1],
        [1, 0.5, 1, 1, 0.5],
        [1, 1, 1, 2, 1]]

T2_K = [[1, 1, 1, 1, 1],
        [1, 1, 2, 1, 0.5],
        [1, 0.5, 1, 0.5, 2],
        [1, 1, 2, 1, 1],
        [1, 2, 0.5, 1, 1]]

In [198]:
F_T = [[1, 6], [1/6, 1]]

### Проверка согласованности матриц

In [199]:
def vector_function(matrix):
    matrix = np.array(matrix, dtype=float)
    column_sums = np.sum(matrix, axis=0)
    matrix_new = matrix / column_sums
    row_sums = np.sum(matrix_new, axis=1)
    vector = row_sums / np.sum(row_sums)
    return vector

In [200]:
def cheking_consistency(target_kriterias):
    for i in target_kriterias: 
        vector = vector_function(i)
        lamda_max = np.mean(np.dot(i, vector) / vector)
        IS = (lamda_max - len(vector)) / (len(vector) - 1)
        OS = IS / 1.12
        if OS < 0.1:
            print(f"OS равно {round(OS, 4)}, согласованность приемлема")
        else:
            print(f"OS равно {round(OS, 4)}, согласованность НЕ приемлема")

In [201]:
cheking_consistency(target_kriterias)

OS равно 0.0866, согласованность приемлема
OS равно 0.0829, согласованность приемлема


### Получение вектора приоритетов

In [202]:
T_K_priorities_vector = np.vstack((vector_function(T1_K), vector_function(T2_K))).T
T_K_priorities_vector

array([[0.20756133, 0.18794095],
       [0.23249639, 0.20052836],
       [0.20210678, 0.18390054],
       [0.14352092, 0.21871018],
       [0.21431457, 0.20891997]])

In [203]:
A_K_priorities_vector = np.vstack((vector_function(K1_A), 
                                   vector_function(K2_A),
                                   vector_function(K3_A),
                                   vector_function(K4_A),
                                   vector_function(K5_A)))
A_K_priorities_vector

array([[0.75      , 0.25      ],
       [0.8       , 0.2       ],
       [0.16666667, 0.83333333],
       [0.11111111, 0.88888889],
       [0.85714286, 0.14285714]])

In [204]:
F_T_vector = vector_function(F_T)
F_T_vector

array([0.85714286, 0.14285714])

In [205]:
A_T = np.dot(T_K_priorities_vector.T, A_K_priorities_vector).T
A_T

array([[0.57499755, 0.53540388],
       [0.42500245, 0.46459612]])

In [206]:
final = np.dot(A_T, F_T_vector)
final

array([0.56934131, 0.43065869])

Вывод: открываем в городе А